#ifndef ERRORMESSAGE_H
#define ERRORMESSAGE_H
class ErrorMessage {
public:
    static void Post(int) {}
    static void PrintAllErrors() {}
    static void SetTime(int) {}
};

enum {
    ERR_BMS_TIMEOUT,
    ERR_BMS_FAULT,
    ERR_BMS_CONTACTOR_FAULT,
    ERR_DCDC_HEATER_SHORTED,
    ERR_DCDC_OVERTEMP,
    ERR_DCDC_OUTPUT_UNDERVOLT,
    ERR_DCDC_BIAS,
    ERR_DCDC_INPUT_NOT_OK,
    ERR_DCDC_OUTPUT_OVERVOLT,
    ERR_DCDC_CURRENT_LIMITED,
    ERR_DCDC_HEATER_OPEN,
    ERR_DCDC_TIMEOUT,
    ERR_DCDC_COOLANT_REQUEST,
    ERR_DCDC_THERMAL_LIMIT,
    ERR_DCDC_VOLTAGE_REG_FAULT,
    ERR_DCDC_CALIBRATION_FAULT
};
#endif
