#ifndef ERRORMESSAGE_PRJ_H_INCLUDED
#define ERRORMESSAGE_PRJ_H_INCLUDED

#define ERROR_BUF_SIZE 4

#define ERROR_MESSAGE_LIST                                           \
   ERROR_MESSAGE_ENTRY(TESTERROR, ERROR_STOP)                        \
   ERROR_MESSAGE_ENTRY(READY_NOT_SET_ON_IGNITION, ERROR_DISPLAY)     \
   ERROR_MESSAGE_ENTRY(READY_DROPPED_DURING_DIAGNOSE, ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(READY_STUCK_ON_IGNITION_OFF, ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(EPS_STARTUP_DCDC_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(VACUUM_INSUFFICIENT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(BMS_TIMEOUT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(BMS_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(BMS_CONTACTOR_FAULT, ERROR_DISPLAY)


#endif // ERRORMESSAGE_PRJ_H_INCLUDED
