#ifndef ERRORMESSAGE_PRJ_H_INCLUDED
#define ERRORMESSAGE_PRJ_H_INCLUDED

#define ERROR_BUF_SIZE 4

#define ERROR_MESSAGE_LIST                                           \
   ERROR_MESSAGE_ENTRY(TESTERROR, ERROR_STOP)                        \
   ERROR_MESSAGE_ENTRY(READY_NOT_SET_ON_IGNITION, ERROR_DISPLAY)     \
   ERROR_MESSAGE_ENTRY(READY_DROPPED_DURING_DIAGNOSE, ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(READY_STUCK_ON_IGNITION_OFF, ERROR_DISPLAY) \
   ERROR_MESSAGE_ENTRY(EPS_STARTUP_DCDC_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(VACUUM_INSUFFICIENT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(BMS_TIMEOUT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(BMS_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(BMS_CONTACTOR_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(HEATER_THERMAL_SWITCH_BOOT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(HEATER_CONTACTOR_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(HEATER_THERMAL_SWITCH_STUCK_CLOSED, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(HEATER_THERMAL_SWITCH_STUCK_OPEN, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_HEATER_SHORTED, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_OVERTEMP, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_OUTPUT_UNDERVOLT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_BIAS, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_INPUT_NOT_OK, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_OUTPUT_OVERVOLT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_CURRENT_LIMITED, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_HEATER_OPEN, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_TIMEOUT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_COOLANT_REQUEST, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_THERMAL_LIMIT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_VOLTAGE_REG_FAULT, ERROR_DISPLAY) \
  ERROR_MESSAGE_ENTRY(DCDC_CALIBRATION_FAULT, ERROR_DISPLAY)


#endif // ERRORMESSAGE_PRJ_H_INCLUDED
